### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by E3V3A** [ieee8023/blucat#1]
On your website you have an example of an Nexus 4 running bluecat, which means it works on Android, but the Android platform is [not shown](http://blucat.sourceforge.net/blucat/category/devices/) anywhere. Please write a few lines how to get this working on Android.

**Comment by ieee8023** [comment]
What is shown is a scan of an Android phone from a laptop with blucat running. Blucat only works on Mac and Linux right now.

**Comment by E3V3A** [comment]
What does it take to port it to Android? It seem it should not be that hard to do since many Androids are now also found on laptop HW.
